database:
  type: mysql
  host: localhost
  port: 3306
  database: icinga_db
  user: icingadb
  password: sPB5yjUrMhvbdH4z

redis:
  host: 127.0.0.1
  port: 6380
  password: n47QMMSPXshwhaI3

logging:
  # Default logging level. Can be set to 'fatal', 'error', 'warn', 'info' or 'debug'.
  # If not set, defaults to 'info'.
  level: info

  # Logging output. Can be set to 'console' (stderr) or 'systemd-journald'.
  # If not set, logs to systemd-journald when running under systemd, otherwise stderr.
  output: systemd-journald

  # Interval for periodic logging defined as duration string.
  # A duration string is a sequence of decimal numbers and a unit suffix, such as "20s".
  # Valid units are "ms", "s", "m", "h".
  # Defaults to "20s".
  interval: 20s

  # Map of component-logging level pairs to define a different log level than the default value for each component.
  options:
#    config-sync:
#    database:
#    dump-signals:
#    heartbeat:
#    high-availability:
#    history-sync:
#    overdue-sync:
#    redis:
#    retention:
#    runtime-updates:
#    telemetry:

# Retention is an optional feature to limit the number of days that historical data is available,
# as no historical data is deleted by default.
retention:
  # Number of days to retain full historical data. By default, historical data is retained forever.
#  history-days:

  # Number of days to retain historical data for SLA reporting. By default, it is retained forever.
#  sla-days:

  # Map of history category to number of days to retain its data in order to
  # enable retention only for specific categories or to
  # override the number that has been configured in history-days.
  options:
#    acknowledgement:
#    comment:
#    downtime:
#    flapping:
#    notification:
#    state: